import { ItemReport, AIMatchResult, ChatMessage, NotificationItem } from '@/types/lost-and-found';

export const INITIAL_ITEMS: ItemReport[] = [
  {
    id: 'item_101',
    type: 'LOST',
    title: 'Midnight Blue Leather Tri-Fold Wallet',
    description: 'Leather tri-fold wallet in navy blue with contrast stitching. Contains student ID card, transit card, and a library pass. Scratched on bottom right corner.',
    category: 'Wallets & Bags',
    primaryColor: 'Navy Blue',
    secondaryColor: 'Brown',
    brand: 'Fossil',
    dateReported: '2026-07-26T14:30:00Z',
    dateOccurred: '2026-07-26T11:15:00Z',
    location: {
      venue: 'Main Campus Library',
      areaDetail: '3rd Floor Quiet Study Table #12',
      city: 'Boston, MA',
      latitude: 42.3601,
      longitude: -71.0589,
    },
    images: ['https://picsum.photos/seed/blue_wallet_lost/600/400'],
    ocrText: 'Sarah Jenkins Student ID #8849204 State University',
    aiTags: ['blue-leather', 'fossil-wallet', 'student-id', 'tri-fold'],
    rewardAmount: 25,
    status: 'PENDING_MATCH',
    reporter: {
      userId: 'community_reporter_1',
      name: 'Campus Member',
      email: 'member1@community.edu',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=member1',
      role: 'owner',
    },
    verificationQuestions: [
      'What specific card or photo is inside the clear ID slot?',
      'What initial or monogram is stamped on the inner coin pocket?',
      'How much cash/denomination was inside when lost?',
    ],
    qrCodeId: 'QR-LFA-88912',
    createdAt: '2026-07-26T14:30:00Z',
    updatedAt: '2026-07-26T14:30:00Z',
  },
  {
    id: 'item_102',
    type: 'FOUND',
    title: 'Dark Blue Leather Wallet with Campus Cards',
    description: 'Found a navy blue men wallet near the library entrance. Handed over to security desk. Contains ID card and transit pass.',
    category: 'Wallets & Bags',
    primaryColor: 'Navy Blue',
    secondaryColor: 'Dark Brown',
    brand: 'Fossil',
    dateReported: '2026-07-26T15:00:00Z',
    dateOccurred: '2026-07-26T12:00:00Z',
    location: {
      venue: 'Main Campus Library',
      areaDetail: 'Ground Floor Info Counter & Security Gate 1',
      city: 'Boston, MA',
      latitude: 42.3602,
      longitude: -71.0588,
    },
    custodyLocation: 'Campus Security Safe Locker #B-12',
    images: ['https://picsum.photos/seed/blue_wallet_found/600/400'],
    ocrText: 'Sarah Jenkins ID #8849204',
    aiTags: ['navy-blue', 'leather-wallet', 'security-hold', 'campus-id'],
    status: 'PENDING_MATCH',
    reporter: {
      userId: 'community_reporter_2',
      name: 'Campus Samaritan',
      email: 'finder2@citynet.org',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=finder2',
      role: 'finder',
    },
    verificationQuestions: [
      'What is written on the library card inside?',
      'What color is the inner zipper lining?',
    ],
    qrCodeId: 'QR-LFA-88913',
    createdAt: '2026-07-26T15:00:00Z',
    updatedAt: '2026-07-26T15:00:00Z',
  },
  {
    id: 'item_103',
    type: 'LOST',
    title: 'Black iPhone 15 Pro with Clear MagSafe Case',
    description: 'Black titanium iPhone 15 Pro in a clear protective case. Has a small holographic mountain sticker near the camera lens. Wallpaper is a golden retriever dog.',
    category: 'Electronics',
    primaryColor: 'Black',
    secondaryColor: 'Clear',
    brand: 'Apple',
    dateReported: '2026-07-27T08:00:00Z',
    dateOccurred: '2026-07-27T07:30:00Z',
    location: {
      venue: 'Terminal 2 Food Court',
      areaDetail: 'Seating area near Starbucks',
      city: 'Boston Airport, MA',
      latitude: 42.3656,
      longitude: -71.0096,
    },
    images: ['https://picsum.photos/seed/iphone_lost/600/400'],
    aiTags: ['apple-iphone', 'clear-case', 'mountain-sticker', 'magsafe'],
    rewardAmount: 100,
    status: 'PENDING_MATCH',
    reporter: {
      userId: 'community_reporter_3',
      name: 'Airport Traveler',
      email: 'traveler3@mail.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=traveler3',
      role: 'owner',
    },
    verificationQuestions: [
      'What photo or wallpaper appears on the lock screen when powered on?',
      'What sticker or decal is on the back case?',
    ],
    qrCodeId: 'QR-LFA-15PRO',
    createdAt: '2026-07-27T08:00:00Z',
    updatedAt: '2026-07-27T08:00:00Z',
  },
  {
    id: 'item_104',
    type: 'FOUND',
    title: 'Apple Smartphone in Clear Case with Sticker',
    description: 'Found a dark colored Apple iPhone on a food court table. Clear plastic bumper case with a mountain sticker on back. Locked screen.',
    category: 'Electronics',
    primaryColor: 'Black',
    secondaryColor: 'Clear',
    brand: 'Apple',
    dateReported: '2026-07-27T08:45:00Z',
    dateOccurred: '2026-07-27T08:15:00Z',
    location: {
      venue: 'Terminal 2 Airport Info Desk',
      areaDetail: 'Main Information & Lost Property Desk',
      city: 'Boston Airport, MA',
      latitude: 42.3658,
      longitude: -71.0095,
    },
    custodyLocation: 'Airport Customer Service Desk #3 Safe',
    images: ['https://picsum.photos/seed/iphone_found/600/400'],
    aiTags: ['iphone', 'transparent-case', 'airport-found', 'mountain-decal'],
    status: 'PENDING_MATCH',
    reporter: {
      userId: 'community_reporter_4',
      name: 'Terminal Staff',
      email: 'staff4@airport.org',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=staff4',
      role: 'finder',
    },
    createdAt: '2026-07-27T08:45:00Z',
    updatedAt: '2026-07-27T08:45:00Z',
  },
  {
    id: 'item_105',
    type: 'LOST',
    title: 'Gold Frame Prescription Glasses in Ray-Ban Case',
    description: 'Ray-Ban round gold metal wire rimmed glasses. Kept inside a dark brown leather snap closure case.',
    category: 'Jewelry & Watches',
    primaryColor: 'Gold',
    secondaryColor: 'Brown',
    brand: 'Ray-Ban',
    dateReported: '2026-07-25T18:20:00Z',
    dateOccurred: '2026-07-25T16:00:00Z',
    location: {
      venue: 'Central Park South',
      areaDetail: 'Park Bench opposite 59th St entrance',
      city: 'New York, NY',
    },
    images: ['https://picsum.photos/seed/glasses_lost/600/400'],
    aiTags: ['gold-frame', 'rayban-glasses', 'brown-case', 'prescription'],
    status: 'ACTIVE',
    reporter: {
      userId: 'community_reporter_5',
      name: 'City Visitor',
      email: 'visitor5@city.org',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=visitor5',
      role: 'owner',
    },
    createdAt: '2026-07-25T18:20:00Z',
    updatedAt: '2026-07-25T18:20:00Z',
  },
  {
    id: 'item_106',
    type: 'FOUND',
    title: 'Brass Car Key with Red Leather Keyring',
    description: 'Found a set of car keys with a Toyota logo fob and a red braided leather strap near subway gate.',
    category: 'Keys',
    primaryColor: 'Brass',
    secondaryColor: 'Red',
    brand: 'Toyota',
    dateReported: '2026-07-27T09:10:00Z',
    dateOccurred: '2026-07-27T08:50:00Z',
    location: {
      venue: 'Central Station Subway Gate B',
      areaDetail: 'Station Master Booth',
      city: 'Boston, MA',
    },
    custodyLocation: 'Station Master Office Drawer #2',
    images: ['https://picsum.photos/seed/keys_found/600/400'],
    aiTags: ['toyota-key', 'red-keyring', 'subway-found', 'brass-key'],
    status: 'ACTIVE',
    reporter: {
      userId: 'community_reporter_6',
      name: 'Transit Commuter',
      email: 'commuter6@transit.org',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=commuter6',
      role: 'finder',
    },
    createdAt: '2026-07-27T09:10:00Z',
    updatedAt: '2026-07-27T09:10:00Z',
  },
];

export const INITIAL_MATCHES: AIMatchResult[] = [
  {
    id: 'match_901',
    lostItemId: 'item_101',
    foundItemId: 'item_102',
    matchScore: 96,
    overallVerdict: 'HIGH_MATCH',
    visualSimilarityScore: 95,
    textSimilarityScore: 98,
    locationScore: 94,
    colorScore: 97,
    aiReasoning: 'Extremely high likelihood match. Both items describe a navy blue Fossil leather wallet located at the Main Campus Library on the same morning. The OCR text on the ID card matches student Sarah Jenkins (ID #8849204) identically.',
    breakdown: {
      visualDetails: 'Visual match confirmed: Tri-fold navy blue leather texture, identical proportions, and brand stamping.',
      textOcrDetails: 'OCR Match: Exact match for Student ID "Sarah Jenkins ID #8849204".',
      locationTimeDetails: 'Location Coincidence: Lost at 3rd Floor Study Desk vs Found at Library entrance 45 mins later.',
      colorAttributeDetails: 'Attributes: Primary Navy Blue, Fossil brand, Brown secondary trim.',
    },
    status: 'SUGGESTED',
    createdAt: '2026-07-26T15:10:00Z',
  },
  {
    id: 'match_902',
    lostItemId: 'item_103',
    foundItemId: 'item_104',
    matchScore: 92,
    overallVerdict: 'HIGH_MATCH',
    visualSimilarityScore: 90,
    textSimilarityScore: 92,
    locationScore: 95,
    colorScore: 91,
    aiReasoning: 'High confidence match. Both reports feature a black Apple iPhone 15 Pro in a clear case with a holographic mountain sticker on the back, reported within 45 minutes at Terminal 2 Airport.',
    breakdown: {
      visualDetails: 'Visual match: Black chassis in clear bumper case, camera module cutout matches iPhone 15 Pro.',
      textOcrDetails: 'Description text match: Mountain peak sticker mentioned explicitly in both user reports.',
      locationTimeDetails: 'Location match: Terminal 2 Food court vs Terminal 2 Info Desk.',
      colorAttributeDetails: 'Attributes: Black / Clear, Apple brand.',
    },
    status: 'SUGGESTED',
    createdAt: '2026-07-27T08:50:00Z',
  },
];

export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  conv_101_102: [
    {
      id: 'msg_1',
      conversationId: 'conv_101_102',
      senderId: 'system',
      senderName: 'Orbit AI System',
      senderRole: 'admin',
      text: '🤖 High AI Match Detected (96% Confidence). Private conversation initiated between Item Owner and Finder. Personal contact info remains protected.',
      timestamp: '2026-07-26T15:12:00Z',
      isSystem: true,
    },
  ],
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];
